# Generated by Django 3.2.6 on 2021-08-26 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0002_auto_20210817_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 26, 21, 30, 6, 76092), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Telegram'),
        ),
    ]
