# Generated by Django 3.2.6 on 2021-09-07 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0002_auto_20210907_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 13, 19, 21, 79720), null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
