# Generated by Django 3.2.6 on 2021-09-14 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0002_auto_20210912_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meet_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='id встречи'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 14, 11, 44, 57, 404283), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='навыки'),
        ),
    ]
