# Generated by Django 3.2.6 on 2021-09-12 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0003_auto_20210907_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 12, 11, 42, 42, 943085), null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
