# Generated by Django 3.2.6 on 2021-08-29 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0003_auto_20210826_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='feedback',
            new_name='first_feedback',
        ),
        migrations.AddField(
            model_name='meet',
            name='second_feedback',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 17, 28, 0, 758082), null=True),
        ),
    ]
