# Generated by Django 3.2.6 on 2021-08-30 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0004_auto_20210829_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 0, 26, 335148), null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='first_feedback',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='second_profile_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
