# Generated by Django 3.2.6 on 2021-08-12 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0005_auto_20210812_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 15, 43, 35, 257437), null=True),
        ),
    ]
