# Generated by Django 3.2.6 on 2021-08-30 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0007_auto_20210830_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 18, 54, 489692), null=True),
        ),
    ]
