# Generated by Django 3.2.6 on 2021-08-30 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0008_alter_meet_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 24, 18, 86768), null=True),
        ),
    ]
