# Generated by Django 3.2.6 on 2021-08-13 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0009_alter_meet_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 16, 54, 7, 644462), null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='first_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_profile_id', to='filling_profile.profile_for_metting'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='second_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_profile_id', to='filling_profile.profile_for_metting'),
        ),
    ]
