# Generated by Django 3.2.6 on 2021-08-13 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0010_auto_20210813_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='meet_id',
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 16, 59, 52, 314722), null=True),
        ),
    ]
