# Generated by Django 3.2.6 on 2021-08-14 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0011_auto_20210813_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 14, 22, 52, 4, 773453), null=True),
        ),
    ]
