# Generated by Django 3.2.6 on 2021-09-01 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0011_auto_20210901_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 11, 47, 55, 349723), null=True),
        ),
        migrations.DeleteModel(
            name='Ten_Minutes_Meets_Profile_List',
        ),
    ]
