# Generated by Django 3.2.6 on 2021-08-15 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0012_alter_meet_date_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 18, 57, 50, 429736), null=True),
        ),
    ]
