# Generated by Django 3.2.6 on 2021-09-01 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0012_auto_20210901_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 11, 51, 41, 75736), null=True),
        ),
    ]
