# Generated by Django 3.2.6 on 2021-09-01 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0013_alter_meet_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 11, 59, 42, 735044), null=True),
        ),
    ]
