# Generated by Django 3.2.6 on 2021-08-15 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0013_auto_20210815_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 19, 13, 47, 879954), null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='first_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_profile_id', to='filling_profile.profile_for_metting'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='second_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_profile_id', to='filling_profile.profile_for_metting'),
        ),
    ]
