# Generated by Django 3.2.6 on 2021-08-15 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0014_auto_20210815_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 19, 33, 9, 853700), null=True),
        ),
        migrations.AlterField(
            model_name='profile_for_metting',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
