# Generated by Django 3.2.6 on 2021-08-15 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0015_auto_20210815_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 20, 40, 15, 491173), null=True),
        ),
    ]
