# Generated by Django 3.2.6 on 2021-09-02 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0015_alter_meet_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 2, 12, 52, 30, 554656), null=True),
        ),
    ]
