# Generated by Django 3.2.6 on 2021-08-15 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filling_profile', '0016_alter_meet_date_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='first_profile',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='second_profile',
        ),
        migrations.AddField(
            model_name='meet',
            name='first_profile_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='meet',
            name='second_profile_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 20, 44, 30, 469777), null=True),
        ),
        migrations.AlterField(
            model_name='profile_for_metting',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
