# Generated by Django 3.2.6 on 2021-09-01 08:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ten_Minutes_Meet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_profile_id', models.CharField(blank=True, max_length=20)),
                ('second_profile_id', models.CharField(blank=True, max_length=20)),
                ('date_meeting', models.DateField(default=datetime.datetime(2021, 9, 1, 11, 47, 55, 351724), null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('first_feedback', models.CharField(blank=True, max_length=10, null=True)),
                ('second_feedback', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Ten_Minutes_Meet',
            },
        ),
        migrations.CreateModel(
            name='Ten_Minutes_Meets_Profile_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ten_Minutes_Meets_Profile_List',
            },
        ),
    ]
