# Generated by Django 3.2.6 on 2021-09-01 09:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ten_minutes_meet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ten_Minutes_Meets_Profile_List',
            new_name='Ten_Minutes_Profile_List',
        ),
        migrations.AlterField(
            model_name='ten_minutes_meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 12, 4, 59, 691856), null=True),
        ),
        migrations.AlterModelTable(
            name='ten_minutes_profile_list',
            table='Ten_Minutes_Profile_List',
        ),
    ]
