# Generated by Django 3.2.6 on 2021-09-12 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ten_minutes_meet', '0013_alter_ten_minutes_meet_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ten_minutes_meet',
            name='date_meeting',
            field=models.DateField(default=datetime.datetime(2021, 9, 12, 11, 42, 42, 945087), null=True),
        ),
    ]
